### ISSUE TITLE
Diffs associated with comments on Reviews page overrun the width of the main column

### ISSUE THREAD

**Issue by jasonshirtliffNI** [ni/reviewboard-userscripts#12]
I can't see the full width of the diff associated with a comment on the Reviews page of a review. It wraps sometime later, but I can't see the full file path or the rightmost part of the diff.

## Screenshots

![image](https://user-images.githubusercontent.com/66442245/83807029-05188200-a678-11ea-8359-a4444a4e7581.png)

I'm wondering if it's related to this rendering oddity where the comments are narrower than the review summary:
![image](https://user-images.githubusercontent.com/66442245/84074000-710c2a80-a997-11ea-801d-3d8b17bc1e76.png)

## Context

- Extension Version: 1.4.0
- Browser: Chrome 83.0.4103.97 (Official Build) (64-bit)
- URL: https://review-board.natinst.com/r/329115/

**Comment by alejandro5042** [comment]
It's OK to send the link here on GitHub. The link only shows the ID of a review request and the name of an obviously named internal server, all of which is behind VPN and ACL. But also send it to me via Teams if you want! I'd like to see this before I can fix it :P

**Comment by jasonshirtliffNI** [comment]
Edited to include link to a sample review
Also added a second screenshot that may hold a clue (or may not...)

**Comment by alejandro5042** [comment]
Ohhh OK I see. Well it's actually a *feature* :)

Check under the userscript settings:
![image](https://user-images.githubusercontent.com/3143819/84080946-a8cc9f80-a9a2-11ea-9d77-773a6d89bfbe.png)

You have the option of selecting your review width. The userscript default is "readable" but you can go back and select "full width".

But now I just added an option for you to choose what to do on long diffs:

![image](https://user-images.githubusercontent.com/3143819/84084863-e8e35080-a9a9-11ea-8a6b-de81be139cdf.png)

Word wrap looks great! Scrollbars are also nice. Or you can go back to what RB does (hide your diff ;)).

**Comment by alejandro5042** [comment]
Let me know what you think! Closing for now.

**Comment by jasonshirtliffNI** [comment]
1. I like "readability" width, for sure. Especially on a widescreen monitor.
2. Word wrap is nice.

Thank you sir!
