### ISSUE TITLE
A .niconfig reviewer gave a Ship It but it is only reflected in Reviewers, not Note to Reviewers

### ISSUE THREAD

**Issue by xhuff** [ni/reviewboard-userscripts#14]
rossh is a Reviewer and gave a Ship It, but the Note to Reviewers doesn't have a check next to his name, even though it is there in the Reviewers section on the right-hand side

## Screenshots

![image](https://user-images.githubusercontent.com/10565627/84064647-980f3000-a988-11ea-9f10-8be896f1d1c0.png)

## Context

- Extension Version: 1.12.4
- Browser: Chrome 83.0.4103.61
- URL: https://review-board.natinst.com/r/337938/

**Comment by alejandro5042** [comment]
The latest 1.12.4 should fix this! LMK if it doesn't.

**Comment by xhuff** [comment]
Still not fixed in the latest version. I updated the issue to reflect this (1.12.4)
![image](https://user-images.githubusercontent.com/10565627/84065109-6480d580-a989-11ea-94f4-f9628088478a.png)

**Comment by alejandro5042** [comment]
Fixed in latest. Basically I was only enhancing the first instance of each user in that box... needed to do a global replace.
