### ISSUE TITLE
For screenshots, horizontal scrollbar only visible at bottom of the image

### ISSUE THREAD

**Issue by bkeryan** [ni/reviewboard-userscripts#16]
When viewing a large screenshot, both vertical and horizontal scrollbars are always visible. However, with this user script, only the vertical scrollbar is visible at all times; the horizontal scrollbar is only visible when you scroll to the bottom of the image.

## Screenshots

Without userscript, both scrollbars are always visible:
<img width="563" alt="Screen Shot 2020-06-09 at 12 26 42 PM" src="https://user-images.githubusercontent.com/17914399/84180258-d1a96f00-aa4c-11ea-8e79-cf3cb774886b.png">

With userscript, only vertical scrollbar is visible at first:
<img width="496" alt="Screen Shot 2020-06-09 at 12 26 58 PM" src="https://user-images.githubusercontent.com/17914399/84180266-da01aa00-aa4c-11ea-852d-88d9c67650cf.png">

...but when I scroll to the bottom of the image, the horizontal scrollbar is also visible.
<img width="523" alt="Screen Shot 2020-06-09 at 12 27 11 PM" src="https://user-images.githubusercontent.com/17914399/84180303-eab22000-aa4c-11ea-8ed2-cb465ce278d3.png">

## Logs

If applicable, add any relevant messages or errors you see in the browser's JavaScript console.

## Context

- Extension Version: 1.4.0
- Browser: Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- OS: macOS 10.14.6
- URL: https://review-board.natinst.com/r/338456/s/211667/

**Comment by alejandro5042** [comment]
Trying to fix this. Thanks for the report!

**Comment by alejandro5042** [comment]
Fixed in latest version. Please update and verify; reopen or comment if not fixed :)
