### ISSUE TITLE
Dashboard view in Firefox uses limited width and does not fully display show status column on far right

### ISSUE THREAD

**Issue by vijaysitaram** [ni/reviewboard-userscripts#2]
In Firefox 76.0.1 on Windows, the dashboard (incoming review list / default landing page) doesn't take up the full windows width that it does without the plugin (seems optimized for mobile?), and the far right status column is cut off by the scrollbar. See screenshot. This is all if you have not enabled the My Comments column.

## Workaround
Follow the instructions on the nag dialog about dashboard sorting by adding the My Comments column. With the My Comments field added, the width rendering becomes more sane. If you don't have that field enabled, it will nag you on every reload and have the messed up width. If you remove that column, the problem will come back.

## Screenshots

![image](https://user-images.githubusercontent.com/66134815/83286824-38ee3600-a1a6-11ea-83d4-2176c5e7060d.png)

Nag dialog:
![image](https://user-images.githubusercontent.com/66134815/83355305-547f4b00-a324-11ea-9a64-0e293f33e793.png)

Comparison of workaround after adding the sortability "My Comments" column:
![image](https://user-images.githubusercontent.com/66134815/83355399-eedf8e80-a324-11ea-981a-20bc74cd1ab8.png)

## Logs

If applicable, add any relevant messages or errors you see in the browser's JavaScript console.

## Context

- Extension Version: 1.1.2
- Browser: Firefox 76.0.1 64-bit on Windows 10 v1809 64-bit, 
- URL: N/A

**Comment by srkbijili** [comment]
I am also facing the same problem.

**Comment by srkbijili** [comment]
I am seeing the same issue in Chrome also.
Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by vijaysitaram** [comment]
> 
> I am seeing the same issue in Chrome also.
> Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

I was tired of the nag dialog coming up about sortable columns on every load of the incoming/outgoing dashboard and saw that by adding the column, it seems to fix the problem when you do that. It comes back if you turn it off. I've updated the original issue to mention that as a workaround and add new screenshots.

**Comment by alejandro5042** [comment]
Thanks for reporting this! This issue is really two things:

- Nag dialog
- Content width issues

Fixed the nag dialog by only nagging you once. If you dismiss the dialog, you won't get it again.

Fixed the content width issues regardless of whether you have the My Comments column enabled.

Please verify that it is fixed in latest version. (You can force an update by your userscript extension manager settings or extension dropdown.)

**Comment by vijaysitaram** [comment]
Yes, the width issues are definitely solved. I guess I can't check the first-launch dialog on the nag without uninstalling and reinstalling, so let me try that.

**Comment by vijaysitaram** [comment]
Reinstalled and confirmed the nag only shows once. Closing.
