### ISSUE TITLE
Odd repetition of date with new display

### ISSUE THREAD

**Issue by thejcannon** [ni/reviewboard-userscripts#20]
With the new "intelligent" timestamp display I'm seeing some... less-than-intelligent displays 😄 

## Screenshots

![image](https://user-images.githubusercontent.com/3956745/84695929-48dd7800-af11-11ea-905f-752a9266d9f7.png).

## Context

- Extension Version: 1.18.0
- Browser: Chrome 83.0.4103.97
- URL: (if any)

**Comment by alejandro5042** [comment]
Will fix!
