### ISSUE TITLE
Latest prebuild review results are not being parsed by userscript

### ISSUE THREAD

**Issue by alejandro5042** [ni/reviewboard-userscripts#6]
> In a current review, the latest Linux prebuild run suceeded, yet it still shows an X in the meta-data

For some reason, the latest `prebuild` reviews are not being parsed as build results.

## Context

- Extension Version: v1.1.10
- Browser: Chrome
- URL: https://review-board.natinst.com/r/337119/ (NI Internal)

**Comment by xhuff** [comment]
A number of people have also given me a Ship It, but the .niconfig section and the People section hasn't been updated with their responses.

Perhaps this is a case where there are too many revisions for the tool?

**Comment by alejandro5042** [comment]
@xhuff - Please manually update via your userscript manager to v1.1.12 and verify that it is fixed :)

- Problem: Review Board pages its API in 25 items batches.
- Solution: I increased the page size to 200, and now also loop through pages if there is more than one. This means I will parse all reviews and not just the first N.

**Comment by xhuff** [comment]
@alejandro5042 looks like it works now!
![image](https://user-images.githubusercontent.com/10565627/83452574-942a5d80-a41e-11ea-9b21-0e34c7d42af8.png)
