### ISSUE TITLE
Review information sidebar needs to be reorganized

### ISSUE THREAD

**Issue by zhindes** [ni/reviewboard-userscripts#9]
The default view of information looks like this:
![image](https://user-images.githubusercontent.com/42776655/83680207-493b5200-a5a6-11ea-9401-86b4addc8619.png)

With the userscript it looks like this:
![image](https://user-images.githubusercontent.com/42776655/83680273-5f491280-a5a6-11ea-9e21-5043ebf370a9.png)

The most glaring issue is that the Reviewers label seems completely out of place.

**Comment by alejandro5042** [comment]
Weird! I hadn't noticed but should be easy to fix :)

**Comment by alejandro5042** [comment]
The userscript removes what I consider "useless, low-entropy headers." In the latest version, I removed that Reviewers header (I missed it!) but renamed People to Reviewers.

Re-open if you wish another change! Thank you!
